name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install .[test]
          pip install pytest

      - name: Start CockroachDB (latest)
        run: |
          docker run -d \
            --name crdb \
            -p 26257:26257 \
            -p 8080:8080 \
            cockroachdb/cockroach:latest \
            start-single-node --insecure

      - name: Set CRDB_URL environment variable
        run: echo "CRDB_URL=cockroachdb://root@localhost:26257/defaultdb?sslmode=disable" >> $GITHUB_ENV

      - name: Wait for DB to be ready
        run: sleep 5

      - name: Initialize test database
        run: |
          docker exec crdb ./cockroach sql --insecure --host=localhost -e "
            USE defaultdb;
            CREATE TABLE users (
              id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
              name STRING
            );
            INSERT INTO users (name) VALUES
              ('Alice'), ('Bob'), ('Virag'), ('Allen'), ('Andrew'), ('David');
          "

      - name: Build package
        run: python -m build

      - name: Install project
        run: pip install .

      - name: Run all tests
        run: pytest -ra -q -m "not integration or integration"

      - name: Check for log file
        run: test -f logs/crdb_dump.log
